version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shop
      MYSQL_USER: shopuser
      MYSQL_PASSWORD: shoppassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    build:
      context: ./php
    container_name: php-container
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql
