services:
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./public:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "80:80"
        depends_on:
            - php-fpm
        healthcheck:
            test: ["CMD", "nginx", "-t"]
            interval: 3s
            retries: 3

    php-fpm:
        build: .
        container_name: php-fpm
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql
        healthcheck:
            test: ["CMD", "php", "-v"]
            interval: 3s
            retries: 3

    mysql:
        image: bitnami/mysql
        container_name: mysql
        restart: always
        volumes:
            - ./migrations:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 3s
            retries: 3
        environment:
            MYSQL_ROOT_PASSWORD: password

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: password
        depends_on:
            - mysql
